### ISSUE TITLE
several commands in one action

### ISSUE THREAD

**Issue by lsochaSopamo** [Sopamo/via#2]
I tried to add `docker-compose up -d && docker-compose exec app npm run watch ` into `start` but I have the below error
![image](https://user-images.githubusercontent.com/86287030/179469814-c2bdc45c-0b7f-440d-a5f8-79031c345022.png)

**Comment by Sopamo** [comment]
@fieteboerner I see a small coding session in our future :)

**Comment by lsochaSopamo** [comment]
> @fieteboerner I see a small coding session in our future :)

I just hope it'll be the near future. I'd want to use one action :D

**Comment by Sopamo** [comment]
Fixed in https://github.com/Sopamo/via/releases/tag/v0.2.2 🥳
